### ISSUE TITLE
User will fall into the void when teleporting in Spectator mode.

### ISSUE THREAD

**Issue by adsa562** [free-mc-plugins/AnimatedTeleport#3]
User will fall into the void when teleporting in Spectator mode.
Server Build: Spigot 1.15.2
如果玩家在旁觀模式中進行tp或是其他指令移動，在被傳送過去目標點上方後，會直直墜入虛空中死亡。其他模式則不會。

伺服器版本：Spigot 1.15.2

**Comment by eric2788** [comment]
你好，本人親測中途離開是沒有問題的，曾經也有一個人有反映這個問題，但是使用spigot review反映問題。因此我已經在spigot上刪除了本插件，並且放棄維護，歡迎提取源碼重製。
